//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAEM.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAEM.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos necesidades.
        /// </summary>
        public static string DatosNecesidades {
            get {
                return ResourceManager.GetString("DatosNecesidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos proyecto.
        /// </summary>
        public static string DatosProyecto {
            get {
                return ResourceManager.GetString("DatosProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar una necesidad que ya está en proceso..
        /// </summary>
        public static string ErrorDeleteNecesidadEstadoEnProceso {
            get {
                return ResourceManager.GetString("ErrorDeleteNecesidadEstadoEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar una necesidad que ya está finalizada..
        /// </summary>
        public static string ErrorDeleteNecesidadEstadoFinalizada {
            get {
                return ResourceManager.GetString("ErrorDeleteNecesidadEstadoFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la necesidad ya que no se encontró en nuestro sistema..
        /// </summary>
        public static string ErrorDeleteNecesidadNecesidadNoExiste {
            get {
                return ResourceManager.GetString("ErrorDeleteNecesidadNecesidadNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un proyecto debe tener al menos una necesidad..
        /// </summary>
        public static string ErrorProyectoSinNecesidades {
            get {
                return ResourceManager.GetString("ErrorProyectoSinNecesidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha deseable.
        /// </summary>
        public static string FechaDeseable {
            get {
                return ResourceManager.GetString("FechaDeseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más información url.
        /// </summary>
        public static string MasInformacionUrl {
            get {
                return ResourceManager.GetString("MasInformacionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesidades.
        /// </summary>
        public static string Necesidades {
            get {
                return ResourceManager.GetString("Necesidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url imagen.
        /// </summary>
        public static string UrlImagen {
            get {
                return ResourceManager.GetString("UrlImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url video.
        /// </summary>
        public static string UrlVideo {
            get {
                return ResourceManager.GetString("UrlVideo", resourceCulture);
            }
        }
    }
}
